version: '3.0'
services:
  cms:
    build: .
    ports:
      - "0.0.0.0:80:80"
    volumes:
      - ./conf/.htaccess:/var/www/html/.htaccess

  mysql_db:
    image: mysql:5
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=impresscms
   # ports:
     # - "0.0.0.0:3306:3306"
