version: '3.0'
services:
  cms:
    build: .
    ports:
      - "0.0.0.0:80:80"
    volumes:
      - ./conf/.htaccess:/var/www/html/.htaccess

  mysql_db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "0.0.0.0:3306:3306"
