version: '3.0'


volumes:
  db: {}
  
services:
  cms:
    build: .
    ports:
      - "0.0.0.0:80:80"
    volumes:
      - ./conf/.htaccess:/var/www/html/.htaccess

  mysql_db:
    image: mysql:5
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=impresscms
    hostname: "mysql.stage.local"
    volumes:
      #- ./init.db:/docker-entrypoint-initdb.d
      - db:/var/lib/mysql
    #ports:
     # - "0.0.0.0:3306:3306"
